apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "django-app-chart.fullname" . }}-nginx-config
  labels:
    {{- include "django-app-chart.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen 80;

        location /static/ {
            alias /usr/share/nginx/html/static/;
        }

        location /media/ {
            alias /usr/share/nginx/html/media/;
        }

        location / {
            proxy_pass http://localhost:8000; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }