{{- range .Values.volumes }}
{{- if .persistentVolumeClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .persistentVolumeClaim.claimName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi       
  storageClassName: standard
---
{{- end }}
{{- end }}

